[[post]]
category = "Competitive Programming"
title = "Unleashing the Power of Competitive Programming"
subtitle = "A Journey into the World of Algorithms and Problem Solving"
datetime = "2024-01-29"
image = "./config/assets/posts/blog-1.jpg"
url = "https://nrj21.hashnode.dev/unleashing-the-power-of-competitive-programming"

[[post]]
category = "Design"
title = "The Need for Speed"
subtitle = "How Typing Speed Matters for Software Developers"
datetime = "2024-01-29"
image = "./config/assets/posts/blog-2.jpg"
url = "https://nrj21.hashnode.dev/the-need-for-speed"
