[[project]]
title = "Speech Therapy Application"
category = "App development"
image = "./config/assets/projects/project-1.jpg"
url = "https://github.com/Niraj2003/Speech-Therapy-Assessment"

[[project]]
title = "E-Commerce Website"
category = "Web development"
image = "./config/assets/projects/project-2.jpg"
url = "https://github.com/Niraj2003/ECommerce"

[[project]]
title = "Placement Prediction using College Data "
category = "Machine Learning"
image = "./config/assets/projects/project-3.jpg"
url = "https://github.com/Niraj2003/Placement-Prediction"

[[project]]
title = "Blogbook"
category = "Web development"
image = "./config/assets/projects/project-4.jpg"
url = "https://github.com/Niraj2003/BlogBook"

[[project]]
title = "Movies Bucket List"
category = "Web development"
image = "./config/assets/projects/project-5.jpg"
url = "https://github.com/Niraj2003/MyMovies"