############## Education config #################
#################################################
[[education]]
title = "Jaihind High school, Dhule"
timeline = "2017 — 2018"
description = "SSC - 91.80%"

[[education]]
title = "Dr. J. K. Wani Jr. College, Dhule"
timeline = "2019 — 2020"
description = """
  HSC (PCM) - 77.69,
  MHTCET - 97.11%ile,
  JEE Mains - 93.61%ile
"""

[[education]]
title = "Vishwakarma Institute of Information Technology, Pune"
timeline = "2021 — 2024"
description = "CGPA - 9.23"


############## Experience config ################
#################################################
[[experience]]
title = "Technical and Project Team @VIIT IoT Forum"
timeline = "2021 — 2022"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."

[[experience]]
title = "Software Developer Intern @NxtPe"
timeline = "2024 — Present"
description = "Nemo enim ipsam voluptatem blanditiis praesentium voluptum delenit atque corrupti, quos dolores et qvuas molestias exceptur."


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = false
show_value = false

[[skill]]
title = "Web Development"
value = "70%"

[[skill]]
title = "App Development"
value = "90%"

[[skill]]
title = "Data Structure and Algorithm"
value = "80%"

[[skill]]
title = "WordPress"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = false
show_value = false

[[language]]
title = "English"
value = "60%"

[[language]]
title = "Hindi"
value = "50%"